version: '1.1'
services:
  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 

  friend-service:
    build: ./service
    image: friend-service
    depends_on:
      - mongo
    volumes:
      - ./service:/service
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017