version: '1.1'
services:
  mongo:
    image: mongo:latest
    logging: 
      driver: "none"

  friend-service:
    build: ./service
    image: friend-service
    env_file:
      - ./service/mqtt_config.env
    depends_on:
      - mongo
    volumes:
      - ./service:/service
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017